server:
  port: 8808
  servlet:
    context-path: /WeChatPublicService
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/wechatservice?autoReconnect=true&useUnicode=true&characterEncoding=utf8
      username: root
      password:
      #连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      #连接等待超时时间
      max-wait: 30000
      #配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      #配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      #StatViewServlet配置
      stat-view-servlet:
        enabled: true
        #访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:  #密码（默认为空）
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）


#读取映射文件
mybatis:
  mapper-locations: com/wecht/*/mapper/*Mapper.xml

logging:
  config: classpath:log4j2-spring.xml
#微信获取token参数
weChat:
  appId: wxee59ea7b7caaf1b6
  secret: 8a39db1b0532b0cdee34a49b7d16bde1










