
spring:
  profiles:
    active: dev
  datasource:
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #设置单个文件的大小
      max-file-size: 15MB
      #设置总上传的数据大小
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl